# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
   # pre = "<i class=\"fa fa-info-circle\"></i>"
    name = "Syllabus"
    url = "/syllabus/"
    weight = 10
    
[[main]]
    name = "Schedule"
 #    pre = "<i class=\"fa fa-calendar\" aria-hidden=\"true\"></i>"
    url = "/schedule/"
    weight = 20

[[main]]
   # pre = "<i class=\"fa fa-info-circle\"></i>"
    name = "Project"
    url = "/project/"
    weight = 30


[[main]]
    # pre = "<i class=\"fa fa-graduation-cap\" aria-hidden=\"true\"></i>"
    url = "https://canvas.apu.edu"
    name = " Canvas"
    weight = 40


[[main]]
   # pre = "<i class=\"fa fa-question-circle\" aria-hidden=\"true\"></i>"
    name = "Help"
    url = "/help/"
    weight = 60
    
[[main]]
   # pre = "<i class=\"fa fa-question-circle\" aria-hidden=\"true\"></i>"
    name = "Acknowledgments"
    url = "/acknowledgments/"
    weight = 70
    

[[main]]
    url = "https://github.com/kgfitzgerald/APU_MATH250_website"
    name  = "<i class='fab fa-github fa-lg'></i>"
    weight = 90
    
#[[main]]
 #   url = "https://edstem.org/us/courses/8027/discussion/"
  #  name = "<i class=\"fas fa-comments fa-lg\"></i>"
   # weight = 90

    





