# Description for social sharing and search engines.
description = "Website for MATH 250: Data Analysis at Azusa Pacific University"

# Default image for social sharing and search engines. Place image in `static/images/` folder and specify image name here.
sharing_image = ""
twitter_image = ""

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["sta199.css"]
custom_js = ["sta199.js"]

# Define base hex url for index page (where the stickers link out to)
hex_base_url = ""
hex_ext = ""
    
# Define "news" as both articles and events
mainSections = ["articles", "events"]

# options for highlight.js (version, additional languages, and theme)
disable_highlightjs = "true"
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

[footer]
    github_url = "https://github.com/kgfitzgerald/APU_MATH250_website"
    twitter_url = ""
    support = "The website design is derived from  [tidymodels.org](https://www.tidymodels.org) via [https://sta199-fa21-003.netlify.app](https://sta199-fa21-003.netlify.app) with inspiration from [datavizm20](https://datavizm20.classes.andrewheiss.com) and [introds.org](https://introds.org/)."

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[authors]
    show_list = "" # on list page, default is true
    show_single = "" # on single pages, default is true
    show_latest = "" # on bio, default is true
    label_latest = "" # on bio, default is "Latest"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[events]
    link_archive = "" # default is true

# customize your site colors
# these colors get applied by layouts/partials/custom-site.css
# then, the layouts/partials/head_includes.html uses that partial
# the partial head_includes.html is called in the partial header.html everywhere!
[colors]
    text = "#404040" # off-black
    # Links
    link = "#07acac" # main accent
    link_hover = "#07acac" #lighter
    # Footer
    footer_primary = "#4187aa"
    footer_text = "#ffffff" 
    # Backgrounds
    background = "#ffffff" 
    home_section_odd = "#ffffff"
    home_section_even = "#fcfcfc" 
    # Menu
    menu_primary = "#4187aa"
    menu_text = "#ffffff"
    menu_text_active = "#07acac"
    menu_text_current = "#07acac"
    menu_decorate_current = "none"
    menu_title = "#ffffff" 
    menu_title_active = "#07acac" 
    menu_box_hover = "#fcfcfc" 
    menu_box_active = "#fcfcfc" 
    
    # Tables
    header_background = "#1a162d80"
    table_row_even = "#fcfcfc"
    table_row_odd = "#1a162d10"

